# Autostart Programs
exec-once=uwsm finalize
exec-once=app2unit -u noctalia.scope -- noctalia
exec-once=app2unit -u wl-paste.scope -- wl-paste --watch cliphist store
exec=app2unit -u foot-server.scope -- foot --server
