# Monitor Rules

# Built-in display(s)
monitorrule=model:0x1777,width:1920,height:1080,refresh:60,x:3090,y:1000,scale:1,rr:0,vrr:0
monitorrule=model:0x1515,width:1920,height:1080,refresh:60,x:3090,y:1000,scale:1,rr:0,vrr:0

# DP-2 (main) to the right of eDP-1
monitorrule=model:AG276QZD2,width:2560,height:1440,refresh:240,x:5010,y:900,scale:1,rr:0,vrr:0

# DP-3 (work) to the left of eDP-1
monitorrule=model:DELL P3225QE,width:3840,height:2160,refresh:100,x:0,y:0,scale:1.25,rr:0,vrr:0
