[aliases]
[aliases.adate]
command = ["sh", "-c", "adb shell date $(date +%m%d%H%M%Y.%S)"]

[aliases.ag]
command = [
  "ug",
  "-r",
  "--ignore-files",
  "-I",
  "-n",
  "--heading",
  "--break",
  "--color",
  "-j",
  "--sort"
]

[aliases.bunx]
command = ["aubx"]

[aliases.cat]
command = ["bat", "-pp"]

[aliases.diff]
command = ["delta"]
requires = "delta"

[aliases.du]
command = ["dust"]

[aliases.fhere]
command = ["find", ".", "-name"]

[aliases.grep]
command = ["ugrep", "-G"]

[aliases.egrep]
command = ["ugrep", "-E"]

[aliases.myip]
command = ["curl", "http://ipecho.net/plain", ";", "echo"]

[aliases.rg]
command = [
  "ugrep",
  "-r",
  "--ignore-files",
  "--ignore-files=.ignore",
  "--ignore-files=.rgignore",
  "-I",
  "-n",
  "--heading",
  "--break",
  "--color"
]

[aliases.vi]
command = ["nvim"]

[aliases.vim]
command = ["nvim"]
