USE_CCACHE=1
SCCACHE_BIN=${HOME}/.nix-profile/bin/sccache
CCACHE_EXEC=${SCCACHE_BIN}
RUSTC_WRAPPER=${HOME}/.local/bin/sccache-wrapper
SCCACHE_ENABLED=y
SCCACHE_DIR=${HOME}/.cache/sccache
SCCACHE_COMPRESS=1
SCCACHE_MAX_CON_FAILURES=10
SCCACHE_MAX_FRAME_LENGTH=104857600
