# Config for sworkstyle
#
# You can rename workspaces based on the exact application names or by generic pattern.
# When it could not match anything it will use the fallback.
#
# format:
#
# 	'{pattern}' = '{icon}'
#
# pattern: Can either be the exact "app_name" (app_id/class) of the window or a regex string in the format of `"/{regex}/"` which will match the window "title".
# icon: Your beatifull icon
#
# verbose format:
# 
#	'{pattern}' = { type = 'generic' | 'exact', value = '{icon}' }
#
#
# If it couldn't match something it will print:
# 
# WARN [sworkstyle:config] No match for '{app_name}' with title '{title}' 
#
# You can use {title} to do a generic matching 
# You can use {app_name} to do an exact match

fallback = ''

force_ltr = true

[matching]
'/Picture-in-Picture/' = ''
'/Mozilla Firefox/' = ''
'/micro*/' = { type = 'generic', value = 'μ' }
'/ranger/' = { type = 'generic', value = '' }
'/spt/' = { type = 'generic', value = '' }
'Steam' = ''
'vlc' = ''
'Bitwarden' = ''
'Google-chrome' = ''
'Chromium' = ''
'Slack' = ''
'Code' = ''
'code-oss' = ''
'jetbrains-idea-ce' = ''
'Spotify' = ''
'GitHub Desktop' = ''
'firefox' = ''
'Nightly' = ''
'firefoxdeveloperedition' = ''
'/npm/' = ''
'/node/' = ''
'jetbrains-studio' = 'ﲎ'
'lutris' = ''
'yuzu' = ''
'ryujinx' = ''
'Gimp-2.10' = ''
'org.gnome.Nautilus' = ''
'discord' = 'ﭮ'
