nix = { packages = [
  "apktool",
  "aube",
  "bash",
  "bash-completion",
  "bat",
  "bitwarden-cli",
  "btop",
  "bun",
  "cargo",
  "cmake",
  "conventional-changelog-cli",
  "curl",
  "delta",
  "dex2jar",
  "docker-compose",
  "dust",
  "eza",
  "fastfetch",
  "fd",
  { name = "fira-code", options = { installable = "nixpkgs#nerd-fonts.fira-code" } },
  "fzf",
  "gh",
  "git",
  "git-lfs",
  "go",
  "gnumake",
  "grpcurl",
  "gvfs",
  "herdr",
  "htop",
  "jq",
  "just",
  "less",
  "lsof",
  "meson",
  "metapac",
  "mosh",
  "neovim",
  "netcat",
  "nix-search-cli",
  "noto-fonts-color-emoji",
  "oh-my-posh",
  "opencode",
  "openspec",
  "openssh",
  "pandoc",
  "pigz",
  "podman",
  "procs",
  "protobuf",
  "python3",
  { name = "python-lsp-server", options = { installable = "nixpkgs#python3Packages.python-lsp-server" } },
  "ripgrep",
  "rmlint",
  "rsync",
  "ruff",
  "rustc",
  "scrcpy",
  "socat",
  "sshfs",
  "syncthing",
  "tirith",
  "tmux",
  "topgrade",
  "ugrep",
  "unzip",
  "uv",
  "wget",
  "which",
  "yadm",
  "yq-go",
  "zip",
  "zoxide",
  "zsh",
] }
