nix = { packages = [
  "apktool",
  "atuin",
  "aube",
  "bash",
  "bash-completion",
  "bash-env-json",
  "bitwarden-cli",
  "btop",
  "bun",
  "carapace",
  "cargo",
  "cargo-binstall",
  "cmake",
  "curl",
  "dex2jar",
  "docker-compose",
  "fastfetch",
  { name = "fira-code", options = { installable = "nixpkgs#nerd-fonts.fira-code" } },
  "fzf",
  "gh",
  "git",
  "git-lfs",
  "go",
  "gnumake",
  "grpcurl",
  "gvfs",
  { name = "herdr", options = { installable = "github:herdrdev/herdr#herdr" } },
  "jq",
  "less",
  "lsof",
  "metapac",
  "mosh",
  "neovim",
  "netcat",
  "nix-search-cli",
  "noto-fonts-color-emoji",
  "nodejs-slim",
  "nushell",
  "oh-my-posh",
  "openssh",
  "pandoc",
  "pigz",
  "podman",
  "procs",
  "protobuf",
  "rmlint",
  "rsync",
  "rustc",
  "sccache",
  "scrcpy",
  "socat",
  "sshfs",
  "syncthing",
  "tirith",
  "tmux",
  "ugrep",
  "unzip",
  { name = "uv", hooks = { after_install = [
    "uv",
    "python",
    "install",
    "--default"
  ] } },
  "wget",
  "which",
  "yadm",
  "yq-go",
  "zip",
  "zsh",
] }

cargo = { packages = [
  { name = "aubeshim", hooks = { after_install = [
    "aubeshim",
    "install",
    "--force"
  ] } },
  "bat",
  "cargo-update",
  "du-dust",
  "eza",
  "fd-find",
  "git-delta",
  "just",
  { name = "nu_plugin_inc", hooks = { after_install = [
    "nu",
    "-c",
    "plugin add ~/.cargo/bin/nu_plugin_inc"
  ] } },
  { name = "nu_plugin_port_extension", options = { git = "https://github.com/FMotalleb/nu_plugin_port_extension" }, hooks = { after_install = [
    "nu",
    "-c",
    "plugin add ~/.cargo/bin/nu_plugin_port_extension"
  ] } },
  { name = "nu_plugin_query", hooks = { after_install = [
    "nu",
    "-c",
    "plugin add ~/.cargo/bin/nu_plugin_query"
  ] } },
  { name = "rtk", options = { git = "https://github.com/rtk-ai/rtk" } },
  "topgrade",
  "zoxide",
] }

npm = { packages = [
  "@fission-ai/openspec",
  "conventional-changelog",
  "@microsoft/inshellisense",
  "opencode-ai",
] }

uv = { packages = [
  "ipython",
  "meson",
  "ocgc",
  "pre-commit",
  "pyright",
  "python-lsp-server",
  "ruff",
] }
