nix = { packages = [
  "apktool",
  "aube",
  { name = "bash", options = { installable = "nixpkgs#bash" } },
  "bash-completion",
  "bat",
  "bitwarden-cli",
  "btop",
  "bun",
  "cargo",
  "cmake",
  "conventional-changelog-cli",
  "curl",
  "delta",
  "dex2jar",
  "docker-compose",
  { name = "dust", options = { installable = "nixpkgs#dust" } },
  "eza",
  "fastfetch",
  "fd",
  { name = "fira-code", options = { installable = "nixpkgs#nerd-fonts.fira-code" } },
  "fzf",
  "gh",
  "git",
  "git-lfs",
  "go",
  "gnumake",
  "grpcurl",
  "gvfs",
  "herdr",
  "htop",
  { name = "ipython", options = { installable = "nixpkgs#python3Packages.ipython" } },
  "jq",
  "just",
  "lazygit",
  "less",
  "lsof",
  "meson",
  "metapac",
  "mosh",
  "neovim",
  { name = "netcat", options = { installable = "nixpkgs#netcat" } },
  "nix-search-cli",
  "nodejs-slim",
  "noto-fonts-color-emoji",
  "oh-my-posh",
  "opencode",
  "openspec",
  "openssh",
  { name = "pandoc", options = { installable = "nixpkgs#pandoc" } },
  "pigz",
  "podman",
  "procs",
  "protobuf",
  "python3",
  { name = "python-lsp-server", options = { installable = "nixpkgs#python3Packages.python-lsp-server" } },
  "ripgrep",
  "rmlint",
  "rsync",
  "ruff",
  "rustc",
  "scrcpy",
  { name = "sshfs", options = { installable = "nixpkgs#sshfs" } },
  "syncthing",
  "tailscale",
  "tirith",
  "tmux",
  "topgrade",
  "ugrep",
  "unzip",
  "uv",
  "wget",
  "which",
  "yadm",
  "yq-go",
  "zellij",
  "zimfw",
  "zip",
  "zoxide",
  "zsh",
] }
