flatpak = { packages = [
  { name = "system:com.bitwig.BitwigStudio", options = { remote = "flathub" }, hooks = { after_sync = ["bootstrap-orcaslicer"] } },
  { name = "system:com.github.wwmm.easyeffects", options = { remote = "flathub" } },
  { name = "system:com.jetbrains.IntelliJ-IDEA-Ultimate", options = { remote = "flathub" } },
  { name = "system:com.jetbrains.RustRover", options = { remote = "flathub" } },
  { name = "system:com.obsproject.Studio", options = { remote = "flathub" } },
  { name = "system:com.slack.Slack", options = { remote = "flathub" } },
  { name = "system:com.spotify.Client", options = { remote = "flathub" } },
  { name = "system:com.stremio.Stremio", options = { remote = "flathub" } },
  { name = "system:com.usebottles.bottles", options = { remote = "flathub" } },
  { name = "system:com.valvesoftware.Steam", options = { remote = "flathub" } },
  { name = "system:dev.edfloreshz.CosmicTweaks", options = { remote = "flathub" } },
  { name = "system:dev.vencord.Vesktop", options = { remote = "flathub" } },
  { name = "system:hu.irl.cameractrls", options = { remote = "flathub" } },
  { name = "system:im.riot.Riot", options = { remote = "flathub" } },
  { name = "system:io.freetubeapp.FreeTube", options = { remote = "flathub" } },
  { name = "system:io.github.Soundux", options = { remote = "flathub" } },
  { name = "system:io.itch.itch", options = { remote = "flathub" } },
  { name = "system:io.podman_desktop.PodmanDesktop", options = { remote = "flathub" } },
  { name = "system:net.davidotek.pupgui2", options = { remote = "flathub" } },
  { name = "system:org.chromium.Chromium", options = { remote = "flathub" } },
  { name = "system:org.freecad.FreeCAD", options = { remote = "flathub" } },
  { name = "system:org.ghidra_sre.Ghidra", options = { remote = "flathub" } },
  { name = "system:org.gnome.World.PikaBackup", options = { remote = "flathub" } },
  { name = "system:org.prismlauncher.PrismLauncher", options = { remote = "flathub" } },
  { name = "system:org.tigervnc.vncviewer", options = { remote = "flathub" } },
  { name = "system:org.torproject.torbrowser-launcher", options = { remote = "flathub" } },
  { name = "system:org.videolan.VLC", options = { remote = "flathub" } },
] }
