flatpak = { packages = [
  { name = "user:com.bitwig.BitwigStudio", options = { remote = "flathub" } },
  { name = "user:com.github.wwmm.easyeffects", options = { remote = "flathub" } },
  { name = "user:com.obsproject.Studio", options = { remote = "flathub" } },
  { name = "user:com.slack.Slack", options = { remote = "flathub" } },
  { name = "user:com.spotify.Client", options = { remote = "flathub" } },
  { name = "user:com.stremio.Stremio", options = { remote = "flathub" } },
  { name = "user:com.valvesoftware.Steam", options = { remote = "flathub" } },
  { name = "user:dev.edfloreshz.CosmicTweaks", options = { remote = "flathub" } },
  { name = "user:dev.vencord.Vesktop", options = { remote = "flathub" } },
  { name = "user:im.riot.Riot", options = { remote = "flathub" } },
  { name = "user:io.freetubeapp.FreeTube", options = { remote = "flathub" } },
  { name = "user:io.itch.itch", options = { remote = "flathub" } },
  { name = "user:net.davidotek.pupgui2", options = { remote = "flathub" } },
  { name = "user:org.chromium.Chromium", options = { remote = "flathub" } },
  { name = "user:org.freecad.FreeCAD", options = { remote = "flathub" } },
  { name = "user:org.ghidra_sre.Ghidra", options = { remote = "flathub" } },
  { name = "user:org.gnome.World.PikaBackup", options = { remote = "flathub" } },
  { name = "user:org.prismlauncher.PrismLauncher", options = { remote = "flathub" } },
  { name = "user:org.torproject.torbrowser-launcher", options = { remote = "flathub" } },
  { name = "user:org.videolan.VLC", options = { remote = "flathub" } },
] }
