aur_helper = "yay" # AUR helper to use on Arch Linux (paru, yay, ...)
aur_rm_args = [
  "-cns",
] # additional args to pass to AUR helper when removing packages (optional)
disabled_backends = [
] # backends that pacdef should not manage, e.g. ["python"], this can reduce runtime if the package manager is notoriously slow (like pip)

warn_not_symlinks = false  # warn if a group file is not a symlink
flatpak_systemwide = false # whether flatpak packages should be installed system-wide or per user
pip_binary = "pipx"        # choose whether to use pipx instead of pip for python package management (see below, 'pitfalls while using pipx')
