[bootstrap.packages]
"flatpak:com.bitwig.BitwigStudio" = "latest"
"flatpak:com.github.wwmm.easyeffects" = "latest"
"flatpak:com.jetbrains.IntelliJ-IDEA-Ultimate" = "latest"
"flatpak:com.jetbrains.RustRover" = "latest"
"flatpak:com.obsproject.Studio" = "latest"
"flatpak:com.slack.Slack" = "latest"
"flatpak:com.spotify.Client" = "latest"
"flatpak:com.stremio.Stremio" = "latest"
"flatpak:com.usebottles.bottles" = "latest"
"flatpak:com.valvesoftware.Steam" = "latest"
"flatpak:dev.edfloreshz.CosmicTweaks" = "latest"
"flatpak:dev.vencord.Vesktop" = "latest"
"flatpak:hu.irl.cameractrls" = "latest"
"flatpak:im.riot.Riot" = "latest"
"flatpak:io.freetubeapp.FreeTube" = "latest"
"flatpak:io.github.Soundux" = "latest"
"flatpak:io.itch.itch" = "latest"
"flatpak:io.podman_desktop.PodmanDesktop" = "latest"
"flatpak:net.davidotek.pupgui2" = "latest"
"flatpak:org.chromium.Chromium" = "latest"
"flatpak:org.freecad.FreeCAD" = "latest"
"flatpak:org.ghidra_sre.Ghidra" = "latest"
"flatpak:org.gnome.World.PikaBackup" = "latest"
"flatpak:org.prismlauncher.PrismLauncher" = "latest"
"flatpak:org.tigervnc.vncviewer" = "latest"
"flatpak:org.torproject.torbrowser-launcher" = "latest"
"flatpak:org.videolan.VLC" = "latest"

[bootstrap.hooks.post-packages]
run = "bootstrap-orcaslicer"
