min_version = "2026.7.15"

[settings]
lockfile = false

[settings.npm]
package_manager = "aube_cli"

[env]
MISE_NIX_LINK_PATHS = "bin,sbin,share/man,share/info,share/doc,share/bash-completion,share/zsh,share/fish,share/fonts"

[tools]
oh-my-posh = "latest"
bat = "latest"
eza = "latest"
delta = "latest"
zoxide = "latest"
dust = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
yq = "latest"
ripgrep = "latest"
zellij = "latest"
tmux = "latest"
neovim = "latest"
git-lfs = "latest"
"asdf:mise-plugins/mise-make" = "latest"
cmake = "latest"
node = "latest"
go = "latest"
rust = "latest"
gh = "latest"
grpcurl = "latest"
lazygit = "latest"
meson = "latest"
pandoc = "latest"
protoc = "latest"
docker-compose = "latest"
just = "latest"
uv = "latest"
aube = "latest"
python = "latest"
ruff = "latest"
bun = "latest"
btop = "latest"
fastfetch = "latest"
topgrade = "latest"
bitwarden = "latest"
"npm:@fission-ai/openspec" = "latest"
"npm:conventional-changelog" = "latest"
"npm:opencode-ai" = { version = "latest", allow_builds = ["opencode-ai"] }
"aqua:herdrdev/herdr" = "latest"
"pipx:python-lsp-server" = "latest"
"pipx:ipython" = "latest"
