min_version = "2026.7.15"

[settings]
lockfile = false

[settings.npm]
package_manager = "aube_cli"

[plugins]
nix = "https://github.com/jbadeau/mise-nix.git"

[env]
MISE_NIX_LINK_PATHS = "bin,sbin,share/man,share/info,share/doc,share/bash-completion,share/zsh,share/fish,share/fonts"

[tools]
oh-my-posh = "latest"
bat = "latest"
eza = "latest"
delta = "latest"
zoxide = "latest"
dust = "latest"
fd = "latest"
fzf = "latest"
jq = "latest"
yq = "latest"
ripgrep = "latest"
zellij = "latest"
tmux = "latest"
neovim = "latest"
git-lfs = "latest"
"asdf:mise-plugins/mise-make" = "latest"
cmake = "latest"
node = "latest"
go = "latest"
rust = "latest"
gh = "latest"
grpcurl = "latest"
lazygit = "latest"
meson = "latest"
pandoc = "latest"
protoc = "latest"
docker-compose = "latest"
just = "latest"
uv = "latest"
aube = "latest"
python = "latest"
ruff = "latest"
bun = "latest"
btop = "latest"
fastfetch = "latest"
topgrade = "latest"
bitwarden = "latest"
"npm:@fission-ai/openspec" = "latest"
"npm:conventional-changelog" = "latest"
"npm:opencode-ai" = { version = "latest", allow_builds = ["opencode-ai"] }
"aqua:herdrdev/herdr" = "latest"
"github:sheeki03/tirith" = "latest"
"pipx:python-lsp-server" = "latest"
"pipx:ipython" = "latest"
"nix:nixos/nixpkgs#zsh" = "latest"
"nix:nixos/nixpkgs#zimfw" = "latest"
"nix:nixos/nixpkgs#bash" = "latest"
"nix:nixos/nixpkgs#bashInteractive" = "latest"
"nix:nixos/nixpkgs#bash-completion" = "latest"
"nix:nixos/nixpkgs#procs" = "latest"
"nix:nixos/nixpkgs#ugrep" = "latest"
"nix:nixos/nixpkgs#netcat" = "latest"
"nix:nixos/nixpkgs#rsync" = "latest"
"nix:nixos/nixpkgs#git" = "latest"
"nix:nixos/nixpkgs#curl" = "latest"
"nix:nixos/nixpkgs#wget" = "latest"
"nix:nixos/nixpkgs#openssh" = "latest"
"nix:nixos/nixpkgs#mosh" = "latest"
"nix:nixos/nixpkgs#sshfs" = "latest"
"nix:nixos/nixpkgs#less" = "latest"
"nix:nixos/nixpkgs#which" = "latest"
"nix:nixos/nixpkgs#unzip" = "latest"
"nix:nixos/nixpkgs#zip" = "latest"
"nix:nixos/nixpkgs#pigz" = "latest"
"nix:nixos/nixpkgs#rmlint" = "latest"
"nix:nixos/nixpkgs#apktool" = "latest"
"nix:nixos/nixpkgs#dex2jar" = "latest"
"nix:nixos/nixpkgs#scrcpy" = "latest"
"nix:nixos/nixpkgs#htop" = "latest"
"nix:nixos/nixpkgs#podman" = "latest"
"nix:nixos/nixpkgs#syncthing" = "latest"
"nix:nixos/nixpkgs#gvfs" = "latest"
"nix:nixos/nixpkgs#tailscale" = "latest"
"nix:nixos/nixpkgs#lsof" = "latest"
"nix:nixos/nixpkgs#nix-search-cli" = "latest"
"nix:nixos/nixpkgs#nerd-fonts.fira-code" = "latest"
"nix:nixos/nixpkgs#noto-fonts-color-emoji" = "latest"
